export const countries = [
  {
    code: 'AND',
    name: 'Андорра',
    short: 'AD',
  }, {
    code: 'AFG',
    name: 'Афганистан',
    short: 'AF',
  }, {
    code: 'ATG',
    name: 'Антигуа и Барбуда',
    short: 'AG',
  }, {
    code: 'AIA',
    name: 'Ангвилла',
    short: 'AI',
  }, {
    code: 'ALB',
    name: 'Албания',
    short: 'AL',
  }, {
    code: 'ARM',
    name: 'Армения',
    short: 'AM',
  }, {
    code: 'AGO',
    name: 'Ангола',
    short: 'AO',
  }, {
    code: 'ATA',
    name: 'Антарктика',
    short: 'AQ',
  }, {
    code: 'ARG',
    name: 'Аргентина',
    short: 'AR',
  }, {
    code: 'ASM',
    name: 'Американские Самоа',
    short: 'AS',
  }, {
    code: 'AUS',
    name: 'Австралия',
    short: 'AU',
  }, {
    code: 'ABW',
    name: 'Аруба',
    short: 'AW',
  }, {
    code: 'ALA',
    name: 'Аландские острова',
    short: 'AX',
  }, {
    code: 'AZE',
    name: 'Азербайджан',
    short: 'AZ',
  }, {
    code: 'BIH',
    name: 'Босния и Герцеговина',
    short: 'BA',
  }, {
    code: 'BRB',
    name: 'Барбадос',
    short: 'BB',
  }, {
    code: 'BGD',
    name: 'Бангладеш',
    short: 'BD',
  }, {
    code: 'BFA',
    name: 'Буркина-Фасо',
    short: 'BF',
  }, {
    code: 'BHR',
    name: 'Бахрейн',
    short: 'BH',
  }, {
    code: 'BDI',
    name: 'Бурунди',
    short: 'BI',
  }, {
    code: 'BEN',
    name: 'Бенин',
    short: 'BJ',
  }, {
    code: 'BLM',
    name: 'Сен-Бартельми',
    short: 'BL',
  }, {
    code: 'BMU',
    name: 'Бермуды',
    short: 'BM',
  }, {
    code: 'BRN',
    name: 'Бруней Даруссалам',
    short: 'BN',
  }, {
    code: 'BOL',
    name: 'Боливия',
    short: 'BO',
  }, {
    code: 'BES',
    name: 'Бонайре, Синт-Эстатиус и Саба',
    short: 'BQ',
  }, {
    code: 'BRA',
    name: 'Бразилия',
    short: 'BR',
  }, {
    code: 'BHS',
    name: 'Багамы',
    short: 'BS',
  }, {
    code: 'BTN',
    name: 'Бутан',
    short: 'BT',
  }, {
    code: 'BVT',
    name: 'Остров Буве',
    short: 'BV',
  }, {
    code: 'BWA',
    name: 'Ботсвана',
    short: 'BW',
  }, {
    code: 'BLR',
    name: 'Беларусь',
    short: 'BY',
  }, {
    code: 'BLZ',
    name: 'Белиз',
    short: 'BZ',
  }, {
    code: 'CCK',
    name: 'Кокосовые острова',
    short: 'CC',
  }, {
    code: 'COD',
    name: 'Демократическая Республика Конго',
    short: 'CD',
  }, {
    code: 'CAF',
    name: 'Центрально-африканская республика',
    short: 'CF',
  }, {
    code: 'COG',
    name: 'Конго',
    short: 'CG',
  }, {
    code: 'CIV',
    name: 'Кот-д\'Ивуар',
    short: 'CI',
  }, {
    code: 'COK',
    name: 'Острова Кука',
    short: 'CK',
  }, {
    code: 'CHL',
    name: 'Чили',
    short: 'CL',
  }, {
    code: 'CMR',
    name: 'Камерун',
    short: 'CM',
  }, {
    code: 'COL',
    name: 'Колумбия',
    short: 'CO',
  }, {
    code: 'CRI',
    name: 'Коста-Рика',
    short: 'CR',
  }, {
    code: 'CPV',
    name: 'Кабо-Верде',
    short: 'CV',
  }, {
    code: 'CUW',
    name: 'Кюрасао',
    short: 'CW',
  }, {
    code: 'CXR',
    name: 'Остров Рождества',
    short: 'CX',
  }, {
    code: 'DJI',
    name: 'Джибути',
    short: 'DJ',
  }, {
    code: 'DMA',
    name: 'Доминика',
    short: 'DM',
  }, {
    code: 'DOM',
    name: 'Доминиканская республика',
    short: 'DO',
  }, {
    code: 'DZA',
    name: 'Алжир',
    short: 'DZ',
  }, {
    code: 'ECU',
    name: 'Эквадор',
    short: 'EC',
  }, {
    code: 'ESH',
    name: 'Западная Сахара',
    short: 'EH',
  }, {
    code: 'ERI',
    name: 'Эритрея',
    short: 'ER',
  }, {
    code: 'ETH',
    name: 'Эфиопия',
    short: 'ET',
  }, {
    code: 'FJI',
    name: 'Фиджи',
    short: 'FJ',
  }, {
    code: 'FLK',
    name: 'Фолклендские (Мальвинские) острова',
    short: 'FK',
  }, {
    code: 'FSM',
    name: 'Федеративные Штаты Микронезии',
    short: 'FM',
  }, {
    code: 'FRO',
    name: 'Фарерские острова',
    short: 'FO',
  }, {
    code: 'GAB',
    name: 'Габон',
    short: 'GA',
  }, {
    code: 'GRD',
    name: 'Гренада',
    short: 'GD',
  }, {
    code: 'GEO',
    name: 'Грузия',
    short: 'GE',
  }, {
    code: 'GUF',
    name: 'Французская Гвиана',
    short: 'GF',
  }, {
    code: 'GGY',
    name: 'Гернси',
    short: 'GG',
  }, {
    code: 'GHA',
    name: 'Гана',
    short: 'GH',
  }, {
    code: 'GIB',
    name: 'Гибралтар',
    short: 'GI',
  }, {
    code: 'GRL',
    name: 'Гренландия',
    short: 'GL',
  }, {
    code: 'GMB',
    name: 'Гамбия',
    short: 'GM',
  }, {
    code: 'GIN',
    name: 'Гвинея',
    short: 'GN',
  }, {
    code: 'GLP',
    name: 'Гваделупа',
    short: 'GP',
  }, {
    code: 'GNQ',
    name: 'Экваториальная Гвинея',
    short: 'GQ',
  }, {
    code: 'SGS',
    name: 'Южная Джорджия и Южные Сандвичевы острова',
    short: 'GS',
  }, {
    code: 'GTM',
    name: 'Гватемала',
    short: 'GT',
  }, {
    code: 'GUM',
    name: 'Гуам',
    short: 'GU',
  }, {
    code: 'GNB',
    name: 'Гвинея-Бисау',
    short: 'GW',
  }, {
    code: 'GUY',
    name: 'Гайана',
    short: 'GY',
  }, {
    code: 'HMD',
    name: 'Остров Херд и острова МакДональд',
    short: 'HM',
  }, {
    code: 'HND',
    name: 'Гондурас',
    short: 'HN',
  }, {
    code: 'HTI',
    name: 'Гаити',
    short: 'HT',
  }, {
    code: 'GRC',
    name: 'Греция',
    short: 'GR',
  }, {
    code: 'AUT',
    name: 'Австрия',
    short: 'AT',
  }, {
    code: 'BEL',
    name: 'Бельгия',
    short: 'BE',
  }, {
    code: 'BGR',
    name: 'Болгария',
    short: 'BG',
  }, {
    code: 'DEU',
    name: 'Германия',
    short: 'DE',
  }, {
    code: 'HKG',
    name: 'Гонконг',
    short: 'HK',
  }, {
    code: 'IDN',
    name: 'Индонезия',
    short: 'ID',
  }, {
    code: 'IRL',
    name: 'Ирландия',
    short: 'IE',
  }, {
    code: 'IMN',
    name: 'Остров Мэн',
    short: 'IM',
  }, {
    code: 'SLV',
    name: 'Сальвадор',
    short: 'SV',
  }, {
    code: 'IOT',
    name: 'Британская территория Индийского океана',
    short: 'IO',
  }, {
    code: 'IRQ',
    name: 'Ирак',
    short: 'IQ',
  }, {
    code: 'IRN',
    name: 'Иран',
    short: 'IR',
  }, {
    code: 'ISL',
    name: 'Исландия',
    short: 'IS',
  }, {
    code: 'JEY',
    name: 'Джерси',
    short: 'JE',
  }, {
    code: 'JAM',
    name: 'Ямайка',
    short: 'JM',
  }, {
    code: 'JOR',
    name: 'Иордания',
    short: 'JO',
  }, {
    code: 'KEN',
    name: 'Кения',
    short: 'KE',
  }, {
    code: 'KGZ',
    name: 'Кыргызстан',
    short: 'KG',
  }, {
    code: 'KHM',
    name: 'Камбоджа',
    short: 'KH',
  }, {
    code: 'KIR',
    name: 'Кирибати',
    short: 'KI',
  }, {
    code: 'COM',
    name: 'Коморские острова',
    short: 'KM',
  }, {
    code: 'KNA',
    name: 'Сент-Китс и Невис',
    short: 'KN',
  }, {
    code: 'PRK',
    name: 'Корейская Народно-Демократическая Республика',
    short: 'KP',
  }, {
    code: 'KWT',
    name: 'Кувейт',
    short: 'KW',
  }, {
    code: 'CYM',
    name: 'Каймановы острова',
    short: 'KY',
  }, {
    code: 'KAZ',
    name: 'Казахстан',
    short: 'KZ',
  }, {
    code: 'LAO',
    name: 'Лаосская Народно-Демократическая Республика',
    short: 'LA',
  }, {
    code: 'LBN',
    name: 'Ливан',
    short: 'LB',
  }, {
    code: 'LCA',
    name: 'Сент-Люсия',
    short: 'LC',
  }, {
    code: 'LIE',
    name: 'Лихтенштейн',
    short: 'LI',
  }, {
    code: 'LKA',
    name: 'Шри-Ланка',
    short: 'LK',
  }, {
    code: 'LBR',
    name: 'Либерия',
    short: 'LR',
  }, {
    code: 'LSO',
    name: 'Лесото',
    short: 'LS',
  }, {
    code: 'LUX',
    name: 'Люксембург',
    short: 'LU',
  }, {
    code: 'LBY',
    name: 'Ливия',
    short: 'LY',
  }, {
    code: 'MAR',
    name: 'Марокко',
    short: 'MA',
  }, {
    code: 'MCO',
    name: 'Монако',
    short: 'MC',
  }, {
    code: 'MDA',
    name: 'Республика Молдова',
    short: 'MD',
  }, {
    code: 'MAF',
    name: 'Сен-Мартен (Франция)',
    short: 'MF',
  }, {
    code: 'MDG',
    name: 'Мадагаскар',
    short: 'MG',
  }, {
    code: 'MHL',
    name: 'Маршалловы острова',
    short: 'MH',
  }, {
    code: 'MKD',
    name: 'Республика Македония',
    short: 'MK',
  }, {
    code: 'MLI',
    name: 'Мали',
    short: 'ML',
  }, {
    code: 'MMR',
    name: 'Мьянма',
    short: 'MM',
  }, {
    code: 'MNG',
    name: 'Монголия',
    short: 'MN',
  }, {
    code: 'MAC',
    name: 'Аомынь',
    short: 'MO',
  }, {
    code: 'MNP',
    name: 'Острова северной Марианы',
    short: 'MP',
  }, {
    code: 'MTQ',
    name: 'Мартиника',
    short: 'MQ',
  }, {
    code: 'MRT',
    name: 'Мавритания',
    short: 'MR',
  }, {
    code: 'MSR',
    name: 'Монсеррат',
    short: 'MS',
  }, {
    code: 'MUS',
    name: 'Маврикий',
    short: 'MU',
  }, {
    code: 'MWI',
    name: 'Малави',
    short: 'MW',
  }, {
    code: 'MEX',
    name: 'Мексика',
    short: 'MX',
  }, {
    code: 'MYS',
    name: 'Малайзия',
    short: 'MY',
  }, {
    code: 'MOZ',
    name: 'Мозамбик',
    short: 'MZ',
  }, {
    code: 'NAM',
    name: 'Намибия',
    short: 'NA',
  }, {
    code: 'NCL',
    name: 'Новая Каледония',
    short: 'NC',
  }, {
    code: 'NER',
    name: 'Нигер',
    short: 'NE',
  }, {
    code: 'NFK',
    name: 'Остров Норфолк',
    short: 'NF',
  }, {
    code: 'NGA',
    name: 'Нигерия',
    short: 'NG',
  }, {
    code: 'NIC',
    name: 'Никарагуа',
    short: 'NI',
  }, {
    code: 'NPL',
    name: 'Непал',
    short: 'NP',
  }, {
    code: 'NRU',
    name: 'Науру',
    short: 'NR',
  }, {
    code: 'NIU',
    name: 'Ниуэ',
    short: 'NU',
  }, {
    code: 'NZL',
    name: 'Новая Зеландия',
    short: 'NZ',
  }, {
    code: 'OMN',
    name: 'Оман',
    short: 'OM',
  }, {
    code: 'PAN',
    name: 'Панама',
    short: 'PA',
  }, {
    code: 'PER',
    name: 'Перу',
    short: 'PE',
  }, {
    code: 'PYF',
    name: 'Французская Полинезия',
    short: 'PF',
  }, {
    code: 'PNG',
    name: 'Папуа — Новая Гвинея',
    short: 'PG',
  }, {
    code: 'PHL',
    name: 'Филиппины',
    short: 'PH',
  }, {
    code: 'PAK',
    name: 'Пакистан',
    short: 'PK',
  }, {
    code: 'SPM',
    name: 'Сен-Пьер и Микелон',
    short: 'PM',
  }, {
    code: 'PCN',
    name: 'Питкэрн',
    short: 'PN',
  }, {
    code: 'PRI',
    name: 'Пуэрто-Рико',
    short: 'PR',
  }, {
    code: 'PSE',
    name: 'Палестина',
    short: 'PS',
  }, {
    code: 'PLW',
    name: 'Палау',
    short: 'PW',
  }, {
    code: 'PRY',
    name: 'Парагвай',
    short: 'PY',
  }, {
    code: 'REU',
    name: 'Реюньон',
    short: 'RE',
  }, {
    code: 'RUS',
    name: 'Россия',
    short: 'RU',
  }, {
    code: 'RWA',
    name: 'Руанда',
    short: 'RW',
  }, {
    code: 'SAU',
    name: 'Саудовская Аравия',
    short: 'SA',
  }, {
    code: 'SLB',
    name: 'Соломоновы Острова',
    short: 'SB',
  }, {
    code: 'SYC',
    name: 'Сейшельские Острова',
    short: 'SC',
  }, {
    code: 'SDN',
    name: 'Судан',
    short: 'SD',
  }, {
    code: 'SHN',
    name: 'Остров Святой Елены, Остров Вознесения и Тристан-да-Кунья',
    short: 'SH',
  }, {
    code: 'SVN',
    name: 'Словения',
    short: 'SI',
  }, {
    code: 'HUN',
    name: 'Венгрия',
    short: 'HU',
  }, {
    code: 'IND',
    name: 'Индия',
    short: 'IN',
  }, {
    code: 'SJM',
    name: 'Шпицберген и Ян-Майен',
    short: 'SJ',
  }, {
    code: 'SVK',
    name: 'Словакия',
    short: 'SK',
  }, {
    code: 'SLE',
    name: 'Сьерра-Леоне',
    short: 'SL',
  }, {
    code: 'SMR',
    name: 'Сан-Марино',
    short: 'SM',
  }, {
    code: 'SEN',
    name: 'Сенегал',
    short: 'SN',
  }, {
    code: 'SOM',
    name: 'Сомали',
    short: 'SO',
  }, {
    code: 'SUR',
    name: 'Суринам',
    short: 'SR',
  }, {
    code: 'SSD',
    name: 'Южный Судан',
    short: 'SS',
  }, {
    code: 'STP',
    name: 'Сан-Томе и Принсипи',
    short: 'ST',
  }, {
    code: 'SXM',
    name: 'Синт-Мартен (голландская часть)',
    short: 'SX',
  }, {
    code: 'SYR',
    name: 'Сирийская Арабская Республика',
    short: 'SY',
  }, {
    code: 'SWZ',
    name: 'Свазиленд',
    short: 'SZ',
  }, {
    code: 'TCA',
    name: 'Острова Туркс и Каикос',
    short: 'TC',
  }, {
    code: 'TCD',
    name: 'Чад',
    short: 'TD',
  }, {
    code: 'ATF',
    name: 'Французские южные территории',
    short: 'TF',
  }, {
    code: 'TGO',
    name: 'Того',
    short: 'TG',
  }, {
    code: 'TJK',
    name: 'Таджикистан',
    short: 'TJ',
  }, {
    code: 'TKL',
    name: 'Токелау',
    short: 'TK',
  }, {
    code: 'TLS',
    name: 'Восточный Тимор',
    short: 'TL',
  }, {
    code: 'TKM',
    name: 'Туркменистан',
    short: 'TM',
  }, {
    code: 'TON',
    name: 'Тонга',
    short: 'TO',
  }, {
    code: 'TTO',
    name: 'Тринидад и Тобаго',
    short: 'TT',
  }, {
    code: 'TUV',
    name: 'Тувалу',
    short: 'TV',
  }, {
    code: 'TWN',
    name: 'Тайвань',
    short: 'TW',
  }, {
    code: 'TZA',
    name: 'Танзания',
    short: 'TZ',
  }, {
    code: 'UKR',
    name: 'Украина',
    short: 'UA',
  }, {
    code: 'UGA',
    name: 'Уганда',
    short: 'UG',
  }, {
    code: 'UMI',
    name: 'Соединенные штаты Малых  Удаленных островов',
    short: 'UM',
  }, {
    code: 'URY',
    name: 'Уругвай',
    short: 'UY',
  }, {
    code: 'UZB',
    name: 'Узбекистан',
    short: 'UZ',
  }, {
    code: 'VAT',
    name: 'Государство-город Ватикан',
    short: 'VA',
  }, {
    code: 'VCT',
    name: 'Сент-Винсент и Гренадины',
    short: 'VC',
  }, {
    code: 'VEN',
    name: 'Боливарианская Республика Венесуэла',
    short: 'VE',
  }, {
    code: 'VGB',
    name: 'Виргинские острова (Британия)',
    short: 'VG',
  }, {
    code: 'VIR',
    name: 'Виргинские острова (США)',
    short: 'VI',
  }, {
    code: 'VUT',
    name: 'Вануату',
    short: 'VU',
  }, {
    code: 'WLF',
    name: 'Уоллес и Футана',
    short: 'WF',
  }, {
    code: 'WSM',
    name: 'Самоа',
    short: 'WS',
  }, {
    code: 'YEM',
    name: 'Йемен',
    short: 'YE',
  }, {
    code: 'MYT',
    name: 'Майот',
    short: 'YT',
  }, {
    code: 'ZAF',
    name: 'Южная Африка',
    short: 'ZA',
  }, {
    code: 'ZMB',
    name: 'Замбия',
    short: 'ZM',
  }, {
    code: 'ZWE',
    name: 'Зимбабве',
    short: 'ZW',
  }, {
    code: 'ALLW',
    name: 'Весь мир',
  }, {
    code: 'SEAS',
    name: 'Юго Восточная Азия',
  }, {
    code: 'SHEN',
    name: 'Страны Шенгена',
  }, {
    code: 'CAN',
    name: 'Канада',
    short: 'CA',
  }, {
    code: 'ISR',
    name: 'Израиль',
    short: 'IL',
  }, {
    code: 'TUN',
    name: 'Тунис',
    short: 'TN',
  }, {
    code: 'FRA',
    name: 'Франция',
    short: 'FR',
  }, {
    code: 'LVA',
    name: 'Латвия',
    short: 'LV',
  }, {
    code: 'THA',
    name: 'Таиланд',
    short: 'TH',
  }, {
    code: 'CHE',
    name: 'Швейцария',
    short: 'CH',
  }, {
    code: 'CHN',
    name: 'Китай',
    short: 'CN',
  }, {
    code: 'CUB',
    name: 'Куба',
    short: 'CU',
  }, {
    code: 'CYP',
    name: 'Кипр',
    short: 'CY',
  }, {
    code: 'EST',
    name: 'Эстония',
    short: 'EE',
  }, {
    code: 'VNM',
    name: 'Вьетнам',
    short: 'VN',
  }, {
    code: 'USA',
    name: 'США',
    short: 'US',
  }, {
    code: 'TUR',
    name: 'Турция',
    short: 'TR',
  }, {
    code: 'CZE',
    name: 'Чехия',
    short: 'CZ',
  }, {
    code: 'DNK',
    name: 'Дания',
    short: 'DK',
  }, {
    code: 'EGY',
    name: 'Египет',
    short: 'EG',
  }, {
    code: 'ESP',
    name: 'Испания',
    short: 'ES',
  }, {
    code: 'FIN',
    name: 'Финляндия',
    short: 'FI',
  }, {
    code: 'GBR',
    name: 'Великобритания',
    short: 'GB',
  }, {
    code: 'HRV',
    name: 'Хорватия',
    short: 'HR',
  }, {
    code: 'ITA',
    name: 'Италия',
    short: 'IT',
  }, {
    code: 'JPN',
    name: 'Япония',
    short: 'JP',
  }, {
    code: 'KOR',
    name: 'Корея',
    short: 'KR',
  }, {
    code: 'LTU',
    name: 'Литва',
    short: 'LT',
  }, {
    code: 'MNE',
    name: 'Черногория',
    short: 'ME',
  }, {
    code: 'MLT',
    name: 'Мальта',
    short: 'MT',
  }, {
    code: 'MDV',
    name: 'Мальдивы',
    short: 'MV',
  }, {
    code: 'NLD',
    name: 'Нидерланды',
    short: 'NL',
  }, {
    code: 'NOR',
    name: 'Норвегия',
    short: 'NO',
  }, {
    code: 'PRT',
    name: 'Португалия',
    short: 'PT',
  }, {
    code: 'QAT',
    name: 'Катар',
    short: 'QA',
  }, {
    code: 'SRB',
    name: 'Сербия',
    short: 'RS',
  }, {
    code: 'SGP',
    name: 'Сингапур',
    short: 'SG',
  }, {
    code: 'ARE',
    name: 'ОАЭ',
    short: 'AE',
  }, {
    code: 'POL',
    name: 'Польша',
    short: 'PL',
  }, {
    code: 'ROU',
    name: 'Румыния',
    short: 'RO',
  }, {
    code: 'SWE',
    name: 'Швеция',
    short: 'SE',
  },
];

export const getCounties = (searchQuery, maxAmount = 0) => {
  const results = [];

  for (let i = 0; i < countries.length; i++) {
    if (!searchQuery || (searchQuery && countries[i].name
      && countries[i].name.toLowerCase().indexOf(searchQuery.toLowerCase()) === 0)) {
      results.push(countries[i]);
    }

    if (results.length >= maxAmount && maxAmount !== 0) {
      break;
    }
  }

  results.sort((countryA, countryB) => {
    const nameA = countryA.name.toLowerCase();
    const nameB = countryB.name.toLowerCase();

    if (nameA < nameB) {
      return -1;
    } else if (nameA > nameB) {
      return 1;
    }
    return 0;
  });

  return results;
};
